name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Install Firebase
        run: sudo npm install -g firebase-tools 
      - name: Install Typescript
        run: sudo npm install -g typescript
      - name: Deploy to Firebase
        run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
