name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Install dependencies for functions
        run: cd functions && npm install
      - name: Install Firebase
        run: sudo npm install -g firebase-tools 
      - name: Install Typescript
        run: sudo npm install -g typescript
      - name: Deploy to Firebase
        run: firebase deploy -P dev --token=${{ secrets.FIREBASE_TOKEN }} --non-interactive
